name: 🚀 Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www || exit

            if [ ! -d "nextjs-app/.git" ]; then
              git clone git@github.com:TON_UTILISATEUR_GITHUB/nextjs-app.git nextjs-app
            fi

            cd nextjs-app || exit
            git pull origin main

            if [ -f "docker-compose.yml" ]; then
              docker compose build
              docker compose down
              docker compose up -d
            else
              echo "Fichier docker-compose.yml introuvable"
              exit 1
            fi
