name: Deploy Next.js app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Set up known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            if [ ! -d /var/www/nextjs-app ]; then
              git clone git@github.com:aigleaboubakar/nextjs-app.git /var/www/nextjs-app
            fi
            cd /var/www/nextjs-app
            git pull origin main
            docker compose build || docker build -t nextjs-app .
            docker compose down || docker stop $(docker ps -q) && docker rm $(docker ps -aq)
            docker compose up -d || docker run -d -p 3000:3000 nextjs-app
          EOF

